# Generated by Django 5.2.1 on 2025-06-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_cv_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cv",
            old_name="category_id",
            new_name="category",
        ),
    ]
