# Generated by Django 5.2.1 on 2025-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_category_created_at_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Görüşülmedi"),
                    ("positive", "Olumlu"),
                    ("negative", "Olumsuz"),
                    ("interviewed", "Görüşüldü"),
                    ("archived", "Arşivlendi"),
                    ("rejected", "Reddedildi"),
                    ("hired", "İşe Alındı"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
    ]
